name: noknokai
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_map: < 8.0.0
  flutter_map_geojson: ^1.0.8
  flutter_riverpod: ^3.0.3
  http: ^1.5.0
  latlong2: any
  nanoid: ^1.0.0
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
